# CircleCI configuration for flaky-test-cypress project
version: 2.1

# Orbs for common tasks
orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@3.3.1

# Define reusable executors
executors:
  node-executor:
    docker:
      - image: cimg/node:20.19-browsers
    resource_class: medium
    working_directory: ~/repo

# Define reusable commands
commands:
  setup-project:
    description: "Checkout code and restore cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

  save-project-cache:
    description: "Save project dependencies cache"
    steps:
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache/Cypress
          key: v1-dependencies-{{ checksum "package-lock.json" }}

# Define jobs
jobs:
  # Job to run tests on the main branch
  test-main:
    executor: node-executor
    steps:
      - setup-project
      - run:
          name: Install dependencies
          command: npm ci --force
      - save-project-cache
      - run:
          name: Start application
          command: npm start
          background: true
      - run:
          name: Wait for application
          command: npx wait-on http://localhost:3000
      - run:
          name: Run Cypress tests
          command: |
            npm test -- --reporter junit --reporter-options "mochaFile=test-results/junit/results-[hash].xml"
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: test-results

  # Job to run tests on specific level branches
  test-level:
    executor: node-executor
    parameters:
      level:
        type: string
        description: "The level branch to test (e.g., level1, level2, etc.)"
    steps:
      - setup-project
      - run:
          name: Checkout level branch
          command: git checkout << parameters.level >>
      - run:
          name: Install dependencies
          command: npm ci
      - save-project-cache
      - run:
          name: Start application
          command: npm start
          background: true
      - run:
          name: Wait for application
          command: npx wait-on http://localhost:3000
      - run:
          name: Run Cypress tests multiple times to detect flakiness
          command: |
            mkdir -p test-results/junit
            echo "Running tests 5 times to detect flaky behavior..."
            for i in {1..5}; do
              echo "Run $i of 5"
              npm test -- --reporter junit --reporter-options "mochaFile=test-results/junit/results-run${i}-[hash].xml" || echo "Test run $i failed"
            done
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: test-results

  # Job using Cypress orb for more advanced features
  cypress-run:
    docker:
      - image: cypress/browsers:node-20.18.0-chrome-130.0.6723.58-1-ff-131.0.3-edge-130.0.2849.52-1
    steps:
      - checkout
      - cypress/install
      - run:
          name: Start application
          command: npm start
          background: true
      - run:
          name: Wait for application
          command: npx wait-on http://localhost:3000
      - cypress/run-tests:
          cypress-command: npx cypress run --reporter junit --reporter-options "mochaFile=test-results/junit/results-[hash].xml"
          start-command: ''  # Empty because we already started the app
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: test-results
      
  # Job for running tests with recording (requires Cypress Dashboard)
  cypress-record:
    docker:
      - image: cypress/browsers:node-20.18.0-chrome-130.0.6723.58-1-ff-131.0.3-edge-130.0.2849.52-1
    steps:
      - checkout
      - cypress/install
      - run:
          name: Start application
          command: npm start
          background: true
      - run:
          name: Wait for application
          command: npx wait-on http://localhost:3000
      - cypress/run-tests:
          cypress-command: npx cypress run --record --parallel --group "parallel tests" --ci-build-id $CIRCLE_SHA1-$CIRCLE_BUILD_NUM --reporter junit --reporter-options "mochaFile=test-results/junit/results-[hash].xml"
          start-command: ''  # Empty because we already started the app
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: test-results

  # Alternative job without using Cypress orb
  cypress-simple:
    executor: node-executor
    steps:
      - setup-project
      - run:
          name: Install dependencies including Cypress
          command: npm ci --force
      - save-project-cache
      - run:
          name: Verify Cypress
          command: npx cypress verify
      - run:
          name: Start application
          command: npm start
          background: true
      - run:
          name: Wait for application
          command: npx wait-on http://localhost:3000
      - run:
          name: Run Cypress tests
          command: |
            mkdir -p test-results/junit
            npx cypress run --reporter junit --reporter-options "mochaFile=test-results/junit/results-[hash].xml"
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/screenshots
          when: always
      - store_artifacts:
          path: cypress/videos
          when: always
      - store_artifacts:
          path: test-results
          when: always

# Define workflows
workflows:
  version: 2
  
  # Default workflow for all branches
  build-and-test:
    jobs:
      - test-main:
          name: "Test Default"
      
      - cypress-simple:
          name: "Cypress Tests"

  # Workflow to test specific level branches
  test-level-branches:
    jobs:
      - test-level:
          name: "Test Level 1"
          level: "level1"
          filters:
            branches:
              only: level1
      
      - test-level:
          name: "Test Level 2"
          level: "level2"
          filters:
            branches:
              only: level2
              
      - test-level:
          name: "Test Level 3"
          level: "level3"
          filters:
            branches:
              only: level3
              
      - test-level:
          name: "Test Level 4"
          level: "level4"
          filters:
            branches:
              only: level4
              
      - test-level:
          name: "Test Level 5"
          level: "level5"
          filters:
            branches:
              only: level5
              
      - test-level:
          name: "Test Level 6"
          level: "level6"
          filters:
            branches:
              only: level6
              
      - test-level:
          name: "Test Level 7"
          level: "level7"
          filters:
            branches:
              only: level7
              
      - test-level:
          name: "Test Level 8"
          level: "level8"
          filters:
            branches:
              only: level8
              
      - test-level:
          name: "Test Level 9"
          level: "level9"
          filters:
            branches:
              only: level9

  # Nightly workflow to test for flakiness
  nightly-flake-detection:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test-main:
          name: "Nightly Main Branch Test"
      
      - cypress-simple:
          name: "Nightly Cypress Tests"

  # Workflow with Cypress Dashboard recording (requires setup)
  recorded-tests:
    jobs:
      - cypress-record:
          name: "Recorded Cypress Tests"
          context: cypress-dashboard
          filters:
            branches:
              only: main
